### ISSUE TITLE
'Invalid field: subsciptions' 

### ISSUE THREAD

**Issue by jerodfritz** [move-zig/icontact-api#3]
If you execute the example code the response will return the following warning(s): 
```
  ...
  warnings: [ 'Invalid field: subsciptions' ] }
```

Even if you rename the field to the correct spelling of subscriptions you'll get a similar error
```
  ...
  warnings: [ 'Invalid field: subscriptions' ] }
```

**How would you suggest creating the contact and subscribing them to a list?**

**Comment by jerodfritz** [comment]
Not sure how to do it with a single call but if 2 are needed here is a PR to update the README
https://github.com/move-zig/icontact-api/commit/5199cec5faf5690fafbe2285277c253224f923e8

**Comment by move-zig** [comment]
Sorry that this got missed for so long. I have updated the documentation in https://github.com/move-zig/icontact-api/pull/4.

As of the time I made the changes to the documentation, adding a subscription at the same time as a contact can only be done in iContact Pro.
